// 预授权的收尾判定。
//
// 这里全是纯函数，没有数据库也没有网络调用——因为这几个判断一旦错了，
// 代价是「活干完了、钱没扣、日历还被清空」，必须能单独测。
//
// 核心区别：`payment_intent.canceled` 这一个事件承载了两件相反的事——
//   1. 有人主动撤销了预授权（客户取消、我们自己取消、后台点 Cancel）；
//   2. 预授权到了 7 天有效期，Stripe 自动释放了资金。
// 第 2 种情况下这一单**多半已经做完了**：下单时预授权，最晚 7 天后到期，
// 而预约本身必须在 7 天内（MAX_ADVANCE_DAYS=7），所以授权到期时预约时刻
// 基本已经过去。把它当成「客户取消」处理，就会把一场真实履约从日历上抹掉。

/**
 * Stripe 自己生成的取消原因。用户侧 API 设不了这几个值——
 * 实测传 `cancellation_reason=automatic` 会被拒：
 *   "The `cancellation_reason` provided in the request is not a valid user provided reason."
 * 所以见到它们，就说明这条取消来自 Stripe 内部而不是某个人的决定。
 *
 * 官方文档（PaymentIntent.cancellation_reason）原文把取消原因分成两类：
 *   user-provided：duplicate / fraudulent / requested_by_customer / abandoned
 *   generated by Stripe internally：failed_invoice / void_invoice / automatic / expired
 * 这里收下**整组**内部原因，而不是只认 'automatic'：到期用哪个词是 Stripe 的
 * 实现细节，只赌一个字符串，哪天它换成 'expired' 我们就会重新开始删日历。
 */
export const STRIPE_INTERNAL_CANCEL_REASONS: ReadonlySet<string> = new Set([
  'automatic', 'expired', 'failed_invoice', 'void_invoice',
]);

export type CancelKind = 'expired' | 'cancelled';

export interface CancelSignals {
  /** pi.cancellation_reason；后台手点 Cancel 时实测为 null */
  reason: string | null | undefined;
  /** 我们在授权时记下的 capture_before；没有就传 null */
  captureBefore: Date | null | undefined;
  now?: Date;
}

export interface CancelVerdict {
  kind: CancelKind;
  /** 落进 cancel_reason 列，便于事后一眼看出是哪条路径判的 */
  why: string;
}

/**
 * 判断一条 payment_intent.canceled 到底是「到期」还是「主动取消」。
 *
 * 两个独立证据，任一成立就算到期：
 *   a) 取消原因属于 Stripe 内部集合（人设不出来）；
 *   b) 我们记录的授权到期时刻已经过去——就算原因字段是空的或换了新词，
 *      钱在那一刻之后本来也已经释放了。
 * 两者都不成立才判为主动取消。这个方向的偏置是刻意的：
 * 误判成「到期」只会多留一份日历记录和一条告警；误判成「取消」会删掉履约记录。
 */
export function classifyCancellation(s: CancelSignals): CancelVerdict {
  const reason = s.reason ?? null;
  if (reason && STRIPE_INTERNAL_CANCEL_REASONS.has(reason)) {
    return { kind: 'expired', why: `authorization_expired:${reason}` };
  }
  const now = s.now ?? new Date();
  if (s.captureBefore && now.getTime() >= new Date(s.captureBefore).getTime()) {
    return { kind: 'expired', why: 'authorization_expired:capture_before_passed' };
  }
  return { kind: 'cancelled', why: reason ?? 'stripe_canceled' };
}

/**
 * 该不该把日历事件删掉。
 *
 * 只删**还没发生**的预约。已经发生过的预约，事件就是履约记录：
 * 授权到期、事后整笔退款都不该让它从日历上消失，否则出了纠纷我们手里什么都没有。
 * settle.ts 的 releaseBooking 早就是这个规矩，这里把它同样应用到 webhook 路径。
 */
export function shouldDropCalendarEvents(startsAt: Date, now: Date = new Date()): boolean {
  return new Date(startsAt).getTime() > now.getTime();
}

/** 授权还剩多久就该开始喊人。7 天的窗口里，留 48 小时给人反应。 */
export const CAPTURE_WARN_HOURS = 48;
/** 再不动手就真的来不及了 */
export const CAPTURE_CRITICAL_HOURS = 24;

export type CaptureLevel = 'ok' | 'warn' | 'critical' | 'expired';

export interface CaptureUrgency {
  hoursLeft: number | null;
  level: CaptureLevel;
}

/**
 * 距离授权失效还有多久，以及紧迫程度。
 * capture_before 为空时返回 'ok'/null——没有这个信息就没法判断，
 * 不能因为字段缺失就天天报警。
 */
export function captureUrgency(
  captureBefore: Date | null | undefined,
  now: Date = new Date(),
): CaptureUrgency {
  if (!captureBefore) return { hoursLeft: null, level: 'ok' };
  const ms = new Date(captureBefore).getTime() - now.getTime();
  const hoursLeft = Math.round(ms / 360_000) / 10;   // 保留一位小数
  if (ms <= 0) return { hoursLeft, level: 'expired' };
  const hours = ms / 3_600_000;
  if (hours <= CAPTURE_CRITICAL_HOURS) return { hoursLeft, level: 'critical' };
  if (hours <= CAPTURE_WARN_HOURS) return { hoursLeft, level: 'warn' };
  return { hoursLeft, level: 'ok' };
}

export interface HoldReleaseSignals {
  status: string;
  paymentIntentId: string | null | undefined;
  /** Stripe 会话状态：open | complete | expired；查不到就传 undefined */
  sessionStatus?: string | null;
  /** 会话上是否已经挂了 PaymentIntent —— 有就说明至少已经发起过扣款 */
  sessionPaymentIntent?: string | null;
}

/**
 * 客户按返回时，能不能放掉他自己的占位。
 *
 * 危险的是"已经付了、webhook 还没到"这一瞬间：那时库里仍是 held、
 * payment_intent_id 仍是空。若这时放掉位子并把订单改成 expired，
 * 随后到达的 onCompleted 会因为「状态不是 held」直接返回——
 * 结果是钱冻结着、日历上没有这一单、位子还被别人订走。
 *
 * 所以只有四个条件同时成立才放手，任何一个拿不准都宁可让客户多等 35 分钟。
 */
export function canReleasePendingHold(s: HoldReleaseSignals): boolean {
  if (s.status !== 'held') return false;
  if (s.paymentIntentId) return false;
  if (s.sessionStatus && s.sessionStatus !== 'open') return false;
  if (s.sessionPaymentIntent) return false;
  return true;
}
