// 预约流程的双语文案。集中在这里，组件里不再出现裸字符串。
// 依 §8219.5，中文页面上的免责声明与费用表必须中英并列——那部分由 Footer 负责，
// 这里只管流程本身的界面文案。

export type Lang = 'en' | 'zh';

export const STRINGS = {
  zh: {
    pageTitle: '在线预约公证',
    steps: ['文件与签署人', '地点', '日期与时间', '确认并支付'],
    tzNote: '所有时间均为太平洋时间',

    s1Title: '第 1 步 · 需要公证什么？',
    s1Sub: '添加每份文件，并选择由谁签署。首次选人时现场填写，之后可直接复用。',
    docN: (n: number) => `文件 ${n}`,
    remove: '移除',
    docTypeLabel: '文件类型（输入可搜索）',
    docTypeSearching: '输入关键词，如「委托」「deed」「军」…',
    docTypePick: '选择或搜索文件类型…',
    noMatch: '没有匹配，选「其他」手动填写',
    otherManual: '✎ 其他（手动填写）',
    freeBadge: 'ⓘ 依法免收公证费',
    docNameLabel: '文件名称',
    docNamePlaceholder: '例：房屋出售委托书',
    actLabel: '公证类型（须由文件本身或收件机构决定）',
    signersLabel: '签署人',
    newSigner: '＋ 新签署人',
    signerCountHint: '数字为该签署人在本文件上需公证的签名处数；同一人以双重身份签署两处（如个人＋受托人）时请用 + 增加。',
    legalNameLabel: '英文法定姓名（与证件一致）',
    legalNamePlaceholder: '例：WEI ZHANG',
    idLabel: '当天出示的证件',
    add: '添加',
    cancel: '取消',
    addDoc: '＋ 添加文件',
    rosterTitle: '签署人信息（当天请携带所列证件）',
    freeStruck: '$0 依法免收',
    summaryLine: (docs: number, acts: number, min: number) =>
      `${docs} 份文件 · ${acts} 个签名处 · 预计服务约 ${min} 分钟`,
    notaryFee: (d: string) => `公证费 ${d}`,
    waivedNote: (n: number) => `（${n} 个签名依法免收）`,
    next: '下一步 →',
    back: '←',
    step1Hint: '每份文件请选择文件类型、公证类型，并至少指定一位签署人。',
    step1HintUnsure: '请先向收件机构确认该文件需要「签名确认 Acknowledgment」还是「宣誓 Jurat」，确认后再回来预约。',

    s2Title: '第 2 步 · 地点',
    s2Sub: '前往我们的服务点可免交通费，上门服务按往返车程估算交通费。',
    mobileTitle: '上门服务（家中 / 办公室 / 医院等）',
    mobileDesc: '另收交通费：按预约时段的往返车程估算，价格与 Uber/Lyft 近似，支付前锁定。',
    parkTitle: '我前往 Sunnyvale Lakewood Park',
    parkDesc: '免交通费，只收公证费。具体见面位置将在确认邮件中提供。',
    addrLabel: '上门地址',
    addrPlaceholder: '输入街道地址，从下拉建议中选择…',
    addrVerified: '✓ 已核验地址：',
    addrChecking: '正在核验地址…',
    addrMustPick: '请从下拉建议中选择一个地址（需精确到街道）。',
    addrNoRoute: '无法规划到该地址的路线，请换一个更完整的地址。',
    addrSearchFailed: '地址搜索暂时不可用，请稍后再试。',
    addrKeyMissing: '地址搜索未配置，请直接来信预约。',
    legLabel: 'Lakewood Park → 上门地点（单程）',
    legValue: (mi: number, min: number) => `${mi} 英里 · 约 ${min} 分钟`,
    peakNote: '此为畅通时段基准值。下一步会按 Google 对每个时段的预测路况分别计算交通费，高峰时段更高。',
    step2Hint: '请填写并核验上门地址。',

    s3Title: '第 3 步 · 日期与时间',
    s3SubMobile: (fee: string) => `下方为各时段的交通费——高峰时段车程更长，交通费更高。公证费 ${fee} 固定不变，合计在下一步确认。`,
    s3SubPark: '在 Lakewood Park 会面免交通费，所有时段同价。',
    dateLabel: '日期',
    dateWindow: (h: number, d: number) => `需至少提前 ${h} 小时预约，最远可约到 ${d} 天以后。`,
    slotsLoading: '正在查询可预约时段…',
    slotsFailed: '暂时无法查询时段，请稍后重试。',
    retry: '重试',
    noSlots: '该日期没有可预约时段，请换一天。',
    slotBusy: '已约满',
    slotFree: '免交通费',
    slotUnavailable: '暂不可约',
    slotTravel: (d: string) => `交通费 ${d}`,
    serviceNote: (min: number, fee: string) => `预计服务约 ${min} 分钟 · 公证费 ${fee} 另计 · 各时段车程为 Google 对该时刻的预测`,
    step3Hint: '请选择一个时段。',

    s4Title: '第 4 步 · 确认并支付',
    s4Sub: '请核对信息。下一步在 Stripe 页面填写邮箱与手机号并付款，付款成功即完成预约。',
    s4SubNoPay: '请核对信息。目前请以邮件方式完成预约，我们会回信确认这个时段。',
    rowDocs: '文件',
    rowTime: '时间',
    rowPlace: '地点',
    rowSigners: '签署人',
    feeLineNotary: (n: number, each: string) => `公证费 ${n} 签名处 × ${each}`,
    feeLineWaived: (n: number) => `依法免收（${n} 签名处）`,
    feeLineTravel: (min: number) => `交通费 往返车程约 ${min} 分钟`,
    feeLineNoTravel: '交通费（Lakewood Park 会面）',
    grandTotal: '合计',
    agreeText: '我已阅读并同意取消与退款政策及交通费说明：48 小时前取消全额退款；24–48 小时取消退公证费、交通费退一半；24 小时内取消、爽约或因证件问题无法完成公证，退公证费、交通费不退。',
    payBtn: (d: string) => `确认并支付 ${d}`,
    holdNote: '🔒 时段为您保留 15 分钟 · 邮箱与手机号在 Stripe 收银台填写',
    holdNote2: '确认函与日历邀请将发送至该邮箱',
    payUnavailable: '在线支付通道尚未开放。',
    payUnavailableCta: '请把以上信息来信告知我们，我们会人工为您确认这个时段。',
    emailUs: '发送预约邮件',
    priceExpired: '报价已过期，请重新选择时段。',
  },
  en: {
    pageTitle: 'Book a notarization',
    steps: ['Documents & signers', 'Location', 'Date & time', 'Confirm & pay'],
    tzNote: 'All times are Pacific Time',

    s1Title: 'Step 1 · What needs notarizing?',
    s1Sub: 'Add each document and choose who signs it. Add a signer once and reuse them across documents.',
    docN: (n: number) => `Document ${n}`,
    remove: 'Remove',
    docTypeLabel: 'Document type (type to search)',
    docTypeSearching: 'Search, e.g. "deed", "power of attorney"…',
    docTypePick: 'Choose or search a document type…',
    noMatch: 'No match — choose "Other" and describe it',
    otherManual: '✎ Other (describe it yourself)',
    freeBadge: 'ⓘ No notarial fee, by law',
    docNameLabel: 'Document name',
    docNamePlaceholder: 'e.g. Power of attorney to sell a house',
    actLabel: 'Notarial act (determined by the document or the receiving agency)',
    signersLabel: 'Signers',
    newSigner: '＋ New signer',
    signerCountHint: 'The number is how many signatures this person has notarized on this document. Use + if one person signs twice in different capacities (e.g. individually and as trustee).',
    legalNameLabel: 'Legal name in English (exactly as on the ID)',
    legalNamePlaceholder: 'e.g. WEI ZHANG',
    idLabel: 'ID to be presented on the day',
    add: 'Add',
    cancel: 'Cancel',
    addDoc: '＋ Add a document',
    rosterTitle: 'Signers (please bring the ID listed for each person)',
    freeStruck: '$0 — waived by law',
    summaryLine: (docs: number, acts: number, min: number) =>
      `${docs} document(s) · ${acts} signature(s) · about ${min} minutes on site`,
    notaryFee: (d: string) => `Notarial fee ${d}`,
    waivedNote: (n: number) => ` (${n} waived by law)`,
    next: 'Next →',
    back: '←',
    step1Hint: 'For each document, choose a type, a notarial act, and at least one signer.',
    step1HintUnsure: 'Please ask the agency requesting the notarization whether it needs an Acknowledgment or a Jurat, then come back to book.',

    s2Title: 'Step 2 · Location',
    s2Sub: 'Meeting us at our spot is free; mobile service adds a travel fee based on round-trip drive time.',
    mobileTitle: 'Mobile service (home / office / hospital)',
    mobileDesc: 'Adds a travel fee estimated from the round-trip drive time for your slot, priced comparably to an Uber/Lyft ride, and locked in before you pay.',
    parkTitle: 'I will come to Sunnyvale Lakewood Park',
    parkDesc: 'No travel fee — notarial fees only. The exact meeting spot is in your confirmation email.',
    addrLabel: 'Service address',
    addrPlaceholder: 'Type a street address, then pick from the suggestions…',
    addrVerified: '✓ Address verified: ',
    addrChecking: 'Verifying address…',
    addrMustPick: 'Please pick an address from the suggestions (street-level detail required).',
    addrNoRoute: 'No driving route to that address. Please try a more complete address.',
    addrSearchFailed: 'Address search is temporarily unavailable. Please try again shortly.',
    addrKeyMissing: 'Address search is not configured. Please email us to book.',
    legLabel: 'Lakewood Park → your location (one way)',
    legValue: (mi: number, min: number) => `${mi} mi · about ${min} min`,
    peakNote: "That's the free-flowing baseline. The next step prices each slot from Google's traffic prediction for that exact departure time, so peak slots cost more.",
    step2Hint: 'Please enter and verify the service address.',

    s3Title: 'Step 3 · Date & time',
    s3SubMobile: (fee: string) => `Below is the travel fee per slot — peak slots take longer to drive, so they cost more. The notarial fee ${fee} does not change; you will see the total on the next step.`,
    s3SubPark: 'Meeting at Lakewood Park is free of travel fees, so every slot is the same price.',
    dateLabel: 'Date',
    dateWindow: (h: number, d: number) => `Book at least ${h} hours ahead, and up to ${d} days out.`,
    slotsLoading: 'Checking available slots…',
    slotsFailed: 'Could not load slots right now. Please try again.',
    retry: 'Retry',
    noSlots: 'No slots available on that date — please pick another day.',
    slotBusy: 'Booked',
    slotFree: 'No travel fee',
    slotUnavailable: 'Unavailable',
    slotTravel: (d: string) => `Travel ${d}`,
    serviceNote: (min: number, fee: string) => `About ${min} minutes on site · notarial fee ${fee} extra · drive times are Google's prediction for each departure time`,
    step3Hint: 'Please choose a time slot.',

    s4Title: 'Step 4 · Confirm & pay',
    s4Sub: 'Please review. On the next screen you will enter your email and phone in Stripe and pay; payment confirms the booking.',
    s4SubNoPay: 'Please review. For now, book by email — we will write back to confirm this slot.',
    rowDocs: 'Document',
    rowTime: 'Time',
    rowPlace: 'Location',
    rowSigners: 'Signers',
    feeLineNotary: (n: number, each: string) => `Notarial fee — ${n} signature(s) × ${each}`,
    feeLineWaived: (n: number) => `Waived by law (${n} signature(s))`,
    feeLineTravel: (min: number) => `Travel fee — about ${min} min round trip`,
    feeLineNoTravel: 'Travel fee (meeting at Lakewood Park)',
    grandTotal: 'Total',
    agreeText: 'I have read and agree to the cancellation and refund policy and the travel-fee terms: cancel more than 48 hours ahead for a full refund; 24–48 hours ahead, notarial fees are refunded and half the travel fee; within 24 hours, a no-show, or if the notarization cannot be completed because of an ID problem, notarial fees are refunded and the travel fee is not.',
    payBtn: (d: string) => `Confirm and pay ${d}`,
    holdNote: '🔒 This slot is held for you for 15 minutes · email and phone are collected by Stripe',
    holdNote2: 'Your confirmation and calendar invite go to that email address',
    payUnavailable: 'Online payment is not open yet.',
    payUnavailableCta: 'Please email us the details above and we will confirm this slot for you by hand.',
    emailUs: 'Email us to book',
    priceExpired: 'This quote has expired. Please pick a slot again.',
  },
} as const;

export const ID_TYPES = {
  zh: ['加州驾照 / 加州 ID', '美国护照', '中国护照', '其他国家护照', '其他州驾照', '美国军人证件'],
  en: ['California driver license / ID', 'U.S. passport', 'Chinese passport', 'Other national passport', 'Out-of-state driver license', 'U.S. military ID'],
} as const;

export const GROUP_LABELS = {
  zh: { common: '常见', free: '依法免收公证费', special: '特殊计费', other: '其他' },
  en: { common: 'Common', free: 'No notarial fee by law', special: 'Special pricing', other: 'Other' },
} as const;

export const RULE_TAGS = {
  zh: { free: '免费', imm: '$15/人封顶', copy: '$15/份', depo: '$30+', standard: '' },
  en: { free: 'Free', imm: '$15 per person cap', copy: '$15 each', depo: '$30+', standard: '' },
} as const;

export const ACTS = [
  { key: 'ack', zh: '签名确认', en: 'Acknowledgment' },
  { key: 'jurat', zh: '宣誓', en: 'Jurat' },
  { key: 'unsure', zh: '不确定', en: 'Not sure' },
] as const;

export const ACT_HINTS = {
  zh: {
    '': '公证员依法不得替您选择公证类型——请依文件上已印好的公证格式，或询问要求您公证的机构。',
    ack: '签名确认：核验您的身份、确认您自愿签署；不涉及文件内容是否属实。',
    jurat: '宣誓：您须当着公证员的面宣誓文件内容属实，并当场签字（不能事先签好）。',
    unsure: '请先向要求您公证的机构问清楚该文件需要哪一种，再回来预约。公证员依法不能替您选择，类型不明当天无法完成公证。',
  },
  en: {
    '': 'A notary may not choose the act for you — go by the certificate already printed on the document, or ask the agency requesting it.',
    ack: 'Acknowledgment: I verify your identity and that you signed willingly. It says nothing about whether the contents are true.',
    jurat: 'Jurat: you swear to me that the contents are true and sign in front of me (it cannot be signed beforehand).',
    unsure: 'Please ask the agency requesting the notarization which one it needs, then come back. A notary may not choose for you, and an unclear act cannot be completed on the day.',
  },
} as const;
